### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by YunL0ngLee** [dotbitHQ/das-contracts#15]
Platform: unbuntu 18.04
Version:1.4.0
Excute command: docker.sh build-all --dev

Failed log:
 error: failed to get `das-types` as a dependency of package `tests v0.1.0 (/code/tests)`

Caused by:
  failed to load source for dependency `das-types`

Caused by:
  Unable to update /das-types/rust

Caused by:
  found a virtual manifest at `/das-types/rust/Cargo.toml` instead of a package manifest

**Comment by linkdesu** [comment]
I have pushed recent commits, and verified it is able to build successfully, please try again.

And there is a few bugs in `docker.sh`, so you may see some errors, but it is OK, just retry your command and it will work.

For example:

```
➜  das-contracts git:(master) ./docker.sh build-all --dev                                                                                                                                                                        Arguments: $is_release=false $feature=dev                                                                                                                                                                                        mv: cannot stat 'target': No such file or directory
Run build command: RUSTFLAGS="-Z pre-link-arg=-zseparate-code -Z pre-link-arg=-zseparate-loadable-segments" cargo build --features "dev" --target riscv64imac-unknown-none-elf && ckb-binary-patcher -i /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type -o /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type
Error: No such container: capsule-dev_home_link_das-contracts-publish_das-contracts
Build contract failed, exit code (1).
➜  das-contracts git:(master) ./docker.sh build-all --dev
Arguments: $is_release=false $feature=dev                                                                                                                                                                                        Run build command: RUSTFLAGS="-Z pre-link-arg=-zseparate-code -Z pre-link-arg=-zseparate-loadable-segments" cargo build --features "dev" --target riscv64imac-unknown-none-elf && ckb-binary-patcher -i /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type -o /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type
Error: No such container: capsule-dev_home_link_das-contracts-publish_das-contracts                                                                                                                                              Build contract failed, exit code (1).
➜  das-contracts git:(master) ./docker.sh start -b
Done ✔
➜  das-contracts git:(master) ./docker.sh build-all --dev
Arguments: $is_release=false $feature=dev
Run build command: RUSTFLAGS="-Z pre-link-arg=-zseparate-code -Z pre-link-arg=-zseparate-loadable-segments" cargo build --features "dev" --target riscv64imac-unknown-none-elf && ckb-binary-patcher -i /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type -o /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type
   Compiling cc v1.0.41
   Compiling autocfg v1.0.1
   Compiling cfg-if v1.0.0
   Compiling typenum v1.12.0
   Compiling version_check v0.9.2
   Compiling crunchy v0.2.2
   Compiling tiny-keccak v2.0.2
   Compiling buddy-alloc v0.4.1
   Compiling cty v0.2.2
   Compiling no-std-compat v0.4.1
   Compiling blake2b-ref v0.3.0
   Compiling opaque-debug v0.3.0
```

**Comment by YunL0ngLee** [comment]
> I have pushed recent commits, and verified it is able to build successfully, please try again.
> 
> And there is a few bugs in `docker.sh`, so you may see some errors, but it is OK, just retry your command and it will work.
> 
> For example:
> 
> ```
> ➜  das-contracts git:(master) ./docker.sh build-all --dev                                                                                                                                                                        Arguments: $is_release=false $feature=dev                                                                                                                                                                                        mv: cannot stat 'target': No such file or directory
> Run build command: RUSTFLAGS="-Z pre-link-arg=-zseparate-code -Z pre-link-arg=-zseparate-loadable-segments" cargo build --features "dev" --target riscv64imac-unknown-none-elf && ckb-binary-patcher -i /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type -o /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type
> Error: No such container: capsule-dev_home_link_das-contracts-publish_das-contracts
> Build contract failed, exit code (1).
> ➜  das-contracts git:(master) ./docker.sh build-all --dev
> Arguments: $is_release=false $feature=dev                                                                                                                                                                                        Run build command: RUSTFLAGS="-Z pre-link-arg=-zseparate-code -Z pre-link-arg=-zseparate-loadable-segments" cargo build --features "dev" --target riscv64imac-unknown-none-elf && ckb-binary-patcher -i /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type -o /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type
> Error: No such container: capsule-dev_home_link_das-contracts-publish_das-contracts                                                                                                                                              Build contract failed, exit code (1).
> ➜  das-contracts git:(master) ./docker.sh start -b
> Done ✔
> ➜  das-contracts git:(master) ./docker.sh build-all --dev
> Arguments: $is_release=false $feature=dev
> Run build command: RUSTFLAGS="-Z pre-link-arg=-zseparate-code -Z pre-link-arg=-zseparate-loadable-segments" cargo build --features "dev" --target riscv64imac-unknown-none-elf && ckb-binary-patcher -i /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type -o /code/target/riscv64imac-unknown-none-elf/debug/account-auction-cell-type
>    Compiling cc v1.0.41
>    Compiling autocfg v1.0.1
>    Compiling cfg-if v1.0.0
>    Compiling typenum v1.12.0
>    Compiling version_check v0.9.2
>    Compiling crunchy v0.2.2
>    Compiling tiny-keccak v2.0.2
>    Compiling buddy-alloc v0.4.1
>    Compiling cty v0.2.2
>    Compiling no-std-compat v0.4.1
>    Compiling blake2b-ref v0.3.0
>    Compiling opaque-debug v0.3.0
> ```
> 
> Oh, and sorry for the inconvinient. 😓

Sorry. It`s still can`nt compile success. 
![image](https://user-images.githubusercontent.com/30599323/177748233-7f5db214-5fe3-42bf-8316-c42455d6fced.png)

![image](https://user-images.githubusercontent.com/30599323/177748092-9b593126-117c-48a3-a7de-fcb383f7fafe.png)

**Comment by linkdesu** [comment]
Oh, You need to pull the das-types repository either.
